# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9314147932b6453eed6253b3025e807628534cd5536f6c7782e421d404827d47b9108b72c341aaf64b7af9661d76967b3ba9dcba4a9ee6d1fdffbe25200afd

test:
  secret_key_base: 8b21794ae46d37acad04ea6fd36b179b1fe67a86bd0a23de1391a6b0eff5f5fd090d3600d41c64e530b27395fb601eed5315a4c17cac643caf95bbf81276988d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
